### ISSUE TITLE
关于请求数据放在created还是mounted中的问题请教

### ISSUE THREAD

**Issue by Jesonhu** [MengZhaoFly/netease_yanxuan#1]
大神你好，我看了你写的这个项目感觉受益很多，但有些地方不明白。
1 初次进入页面的时候，我看到你是在created中发送$dispatch到vuex中获取数据的，现在好像是在mounted中获取数据的，关于这点我想请教下您的理解。

**Comment by MengZhaoFly** [comment]
当时只想着 模版有没有被编译 然后在created做loading的时候就把 数据请求了 。在mounted中更妥

**Comment by Jesonhu** [comment]
@MengZhaoFly 谢谢了
